### ISSUE TITLE
Update .gitignore and remove Pods/ directory

### ISSUE THREAD

**Issue by EgorKolyshkin** [joanb/ChessClockSwift#14]
I think it would be nice to remove this large Pods/ directory from the repository. 
If we do it, then we need to remove .xcworkspace file too. if so, then anyone who wants to clone this repo should then run `pod install`. Cocoapods will install all necessary pods and generate .xcworkspace.

**Comment by joanb** [comment]
That's a nice proposal! feel free to drop a PR! 🚀

**Comment by joanb** [comment]
@all-contributors please add @EgorKolyshkin  for ideas

**Comment by EgorKolyshkin** [comment]
i have created PR, would love you to look at it)

**Comment by joanb** [comment]
Closing because it's already done by @EgorKolyshkin in #17
