### ISSUE TITLE
Stop clocks whenever one reaches 0

### ISSUE THREAD

**Issue by joanb** [joanb/ChessClockSwift#2]

**Comment by l-rettberg** [comment]
Just submitted PR #7.  It doesn't actually "Stop" the clocks, rather keeps the value at 0 when it reaches 0.  I'm not familiar with RxSwift - so that this initial "fix" will address the immediate issue.

**Comment by joanb** [comment]
nice! this is a good project to get in touch with RxSwift. I will asign to you the task.
As a first fix is totally correct , thank you for submiting :)
