### ISSUE TITLE
Use of RxCocoa in ViewController

### ISSUE THREAD

**Issue by davidlamys** [joanb/ChessClockSwift#25]
Hi, just out of curiosity. Is there any particular reason why we use RxSwift but we're not using RxCocoa in the viewcontroller? :)

**Comment by joanb** [comment]
It's just because we are still starting 😅, but RxCocoa  will be a must and would be an awesome contribution here!
The idea is to make the project fully reactive 🚀

**Comment by joanb** [comment]
Closing this since it's already done :) Nice job!
