### ISSUE TITLE
Don't disable both clocks when paused

### ISSUE THREAD

**Issue by joanb** [joanb/ChessClockSwift#31]
Currently, both clocks are disabled when pause button is clicked, but only one is clickable (the one who was ticking when the pause was pressed).
This is a UX problem that may confuse the user. 

The current ticking clock should stay in active status (AKA no alpha applied) when pause button is pressed.

**Comment by jpauljm** [comment]
My PR ;)
https://github.com/joanb/ChessClockSwift/pull/33

**Comment by joanb** [comment]
Thank you a lot for your contribution! 😄 
You are always welcome here 💪 Happy coding!
